server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_registry?createDatabaseIfNotExist=true
    username: root
    password: P@ssW0rd
    driverClassName: com.mysql.cj.jdbc.Driver
